export const organization = {
    name: "House Wolf",
    description: "The House Wolf is a clan-based organization composed of members from multiple backgrounds, united by a common creed, language, and code.  Known primarily as highly-effective explorers and defenders, the House Wolf has, at various points in its history, played a major role as legendary pioneers and protectors in the vast expanse of the Star Citizen universe.",
    logo: "./assets/images/banner2.png",
    join: "https://robertsspaceindustries.com/orgs/CUTTERWOLF",
    web: "https://housewolf.co"
};

export const character = {
    name: "CutterWolf",
    role: "Clan Leader",
    bio: "In the heart of the galaxy, amidst the turmoil of conflict and the ever-shifting tides of power, there emerged a leader whose name became synonymous with the indomitable spirit of the Mandalorian warrior: Cutter Wolf, Clan Leader and Warlord of House Wolf. Born into the crucible of Mandalorian tradition, the journey began humbly, marked by the echoes of automatic weapons fire and the clashing of armor against armor. From his earliest days, he was immersed in the teachings of his people, instilled with the values of honor, resilience, and the unbreakable bond of the clan. His combat skills developed a reputation for unwavering determination and proficiency with weapons. Equipped with his iconic armor and his trusty FS-9, Cutter traversed the galaxy in search of missions to fulfill, adhering strictly to the Mandalorian creed: This is the way. As the years passed, his exploits were not easily counted. Yet, his path to leadership was not paved with silver. It was forged in the fires of adversity, shaped by the trials and tribulations that tested his resolve at every turn. Rising from the ranks of a humble warrior, he embarked on a journey of self-discovery, honing his skills with unwavering determination and an unyielding commitment to his clan. Through blood and sweat, Cutter climbed the ranks of House Wolf, earning the respect and admiration of his fellow warriors with each battle fought and every victory won. His prowess in combat was matched only by his strategic brilliance, his keen mind capable of navigating the treacherous currents of galactic politics with unmatched finesse. As Clan Leader, Cutter Wolf stands as a pillar of strength and unity, his leadership inspiring loyalty and devotion among his followers. Under his guidance, House Wolf has flourished, their influence spreading far and wide across the verse, their reputation as fearsome warriors echoing throughout the galaxy. But his vision extends beyond the battlefield. He was not merely a warrior; he was a visionary, a leader with a dream of a future where Mandalorians could forge their own destiny free from the shackles of oppression and tyranny. Through diplomacy and cunning, he forged alliances with other clans, uniting them under a common banner of honor and solidarity. Yet, even as he stands at the pinnacle of power, Cutter remains ever vigilant, ever prepared to defend his clan against the countless threats that lurk in the shadows. His leadership is a testament to the enduring spirit of the Mandalorian warrior, a beacon of hope in a galaxy consumed by chaos and uncertainty. In the annals of Mandalorian history, the name Cutter Wolf will forever be remembered as a symbol of strength, honor, and the unwavering resolve of a leader who dared to defy the odds and carve his own path amidst the stars. This is the way . . .",
    email: "cutterwolf@housewolf.co"
};
